# Generated by Django 4.1 on 2023-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_prettynum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=7, verbose_name="价格"
            ),
        ),
    ]
