# Generated by Django 4.1 on 2023-11-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_prettynum_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(max_length=128, verbose_name="标题"),
        ),
    ]
