# Generated by Django 4.1 on 2023-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_alter_department_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=63, verbose_name="密码")),
            ],
        ),
    ]
