# Generated by Django 4.1 on 2023-11-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_remove_userinfo_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="size",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
