# Generated by Django 4.1 on 2023-11-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_userinfo_age_userinfo_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="size",),
        migrations.AlterField(
            model_name="userinfo", name="age", field=models.IntegerField(default=2),
        ),
    ]
